import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '../globals.css';

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
// });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="h-full">
            <body className="bg-cover bg-no-repeat bg-gradient-to-br from-[#4A00E0] to-[#8E2DE2] h-full">
                {children}
            </body>
        </html>
    );
}
